name: Build C++ and WebAssembly

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install clang make libsdl2-dev

      - name: Build native
        run: make

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Build WebAssembly
        run: make wasm

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            infinifractal
            infinifractal.js
            infinifractal.wasm
            index.html