name: Build WebAssembly and Deploy

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Build WebAssembly
        run: make wasm

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            infinifractal.js
            infinifractal.wasm
            index.html