name: Build Emscripten and Deploy

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Build
        run: make wasm

      - name: Move outputs
        run: |
          mkdir dist
          mv infinifractal.js dist/
          mv infinifractal.wasm dist/
          cp index.html dist/

      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages publish dist --project-name=infinifractal
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}