name: Build Emscripten and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Build
        run: make wasm

      - name: Move outputs
        run: |
          mv infinifractal.js dist/
          mv infinifractal.wasm dist/

      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy dist --project-name=infinifractal --branch=master
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}